/**
 * Copyright (C) 2007 Google Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.google.inject.tools.ideplugin.eclipse;

/**
 * Text string values of messages in the plugin.
 * 
 * @author Darren Creutz (dcreutz@gmail.com)
 */
final class PluginTextValues {
  public static final String GUICE_PLUGIN_NAME = "Guice Plugin";
  
  //Error messages
  public static final String SELECTION_NOT_JAVA_ELEMENT = "Selection is not a Java element.";
  public static final String SELECTION_NO_BINDINGS = "Selection does not have bindings.";
  public static final String CANNOT_RESOLVE_EDITOR = "Cannot resolve editor";
  
  //Log editor actions
  public static final String CUT = "Cut";
  public static final String COPY = "Copy";
  public static final String PASTE = "Paste";
  public static final String SELECT_ALL = "Select All";
  public static final String CLEAR = "Clear";
  
  //Dialog String
  public static final String GUICE_CONTEXT_CONFIGURATION = "Guice Context Configuration";
  public static final String NO_PROJECT = "No project selected";
  public static final String FIND_NEW_CONTEXTS = "Find New Contexts";
  public static final String SCAN_FOR_CONTEXTS = "Scan for contexts";
  public static final String GLOBAL_OPTIONS = "Global Options";
  public static final String CONTEXT_NAME = "Context Name";
  public static final String FULLY_QUALIFIED_CLASS_NAME = "Fully Qualified Class Name";
  public static final String METHOD_NAME = "Method";
  public static final String CREATE_CONTEXT = "Create a Guice Context";
  public static final String YOUR_CONTEXTS = "Your Module Contexts";
  public static final String CREATE_NEW_CONTEXT = "Create new context";
  public static final String AUTOGENERATED_CONTEXTS = "Autogenerated Module Contexts";
  public static final String NO_CONTEXTS_AVAILABLE = "No Module Contexts Available";
  public static final String ACTIVATE_ALL = "Activate All";
  public static final String DEACTIVATE_ALL = "Deactivate All";
  
  public static final String GUICE_RESULTS = "Guice Results";
  
  public static final String BUILDING_TYPE_HIERARCHY = "Building Guice Type Hierarchy";
  public static final String ANALYZING_TYPE_HIERARCHY = "Analyzing Guice Type Hierarchy";
  
  // Actions text
  public static final String FIND_BINDINGS = "Find Bindings";
  public static final String FIND_BINDINGS_NOT_AVAILABLE = "Cannot find bindings in this scenario";
  public static final String CANNOT_RESOLVE_JAVA_ELEMENT = "Cannot resolve Java element";
  
  public static final String CONFIGURE = "Configure Guice Plugin...";
  public static final String CANNOT_RESOLVE_JAVA_PROJECT = "Cannot resolve Java project";
  
  public static final String RUN_NOW = "Run Module Contexts Now";
  
  public static final String SHOW_GUICE_RESULTS = "Show Guice Bindings View";
  public static final String CANT_OPEN_RESULTS = "Could not open Guice Bindings View";
  
  public static final String SHOW_GUICE_ERRORS = "Show Guice Errors View";
  public static final String CANT_OPEN_ERRORS = "Could not open Guice Errors View";
}
